openapi: 3.0.0
info:
  title: Find Bike api
  description: api for managment of finding stolen bikes.
  version: 1.0.0

servers:
  - url: http://localhost:5000/api

paths:
  #User
  /users:
    $ref: 'api/user.yml'

  /users/{userId}:
    $ref: 'api/user-id.yml'

  /users/{userId}/bikes:
    $ref: 'api/user-id-bike.yml'

  /users/{userId}/bikes/{bikeId}:
    $ref: 'api/bike-id.yml'

  /bikes/{bikeId}:
    $ref: 'api/bike.yml'
  #Officer
  /officer:
    $ref: 'api/officer.yml'

  /officer/{officerId}:
    $ref: 'api/officer-id.yml'

  /officer/{officerId}/jobs:
    $ref: 'api/officer-id-job.yml'

  /officer/{officerId}/jobs/{jobId}:
    $ref: 'api/job-id.yml'

tags:
  - name: user
    description: User enpoints
  - name: officer
    description: Officer endpoints
